// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameExample = "Example"

// Example mapped from table <Example>
type Example struct {
	ID     int32 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Number int32 `gorm:"column:number" json:"number"`
}

// TableName Example's table name
func (*Example) TableName() string {
	return TableNameExample
}
