// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace csharp.Models;

public partial class Example
{
    public int Id { get; set; }

    public int? Number { get; set; }
}