CREATE DATABASE IF NOT EXISTS Test;
USE Test;

CREATE TABLE IF NOT EXISTS Example (
    id INT AUTO_INCREMENT PRIMARY KEY,
    number INT
);

INSERT INTO Example (number) VALUES 
(FLOOR(RAND() * 100)),
(FLOOR(RAND() * 100)),
(FLOOR(RAND() * 100)),
(FLOOR(RAND() * 100)),
(FLOOR(RAND() * 100)),
(FLOOR(RAND() * 100)),
(FLOOR(RAND() * 100)),
(FLOOR(RAND() * 100)),
(FLOOR(RAND() * 100)),
(FLOOR(RAND() * 100)),
(FLOOR(RAND() * 100));
